steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-server-307605/test.server', '-f', 'Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-server-307605/test.server']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'test-server', '--image', 'gcr.io/test-server-307605/test.server', '--region', 'asia-northeast1', '--platform', 'managed', '--allow-unauthenticated']

images: ['gcr.io/test-server-307605/test.server']

timeout: 20m
